version: '3.8'
services:
  nats:
    image: nats:latest
    
  gateway:
    image: disterbia94/tips-gateway:latest
    environment:
      - TZ=Asia/Seoul
    ports:
      - "40000:40000"
    depends_on:
      - inquire
      - email
      - user
      - nats
      - fcm
      - medicine
      - notification
      - emotion
      - exercise
      - video
      - admin
      - check
      - landing
    
  inquire:
    image: disterbia94/tips-inquire-service:latest
    environment:
      - TZ=Asia/Seoul

  email:
    image: disterbia94/tips-email-service:latest
    environment:
      - TZ=Asia/Seoul

  user:
    image: disterbia94/tips-user-service:latest
    environment:
      - TZ=Asia/Seoul

  medicine:
    image: disterbia94/tips-medicine-service:latest
    environment:
      - TZ=Asia/Seoul

  notification:
    image: disterbia94/tips-notification-service:latest
    environment:
      - TZ=Asia/Seoul

  fcm:
    image: disterbia94/tips-fcm-service:latest
    environment:
      - TZ=Asia/Seoul

  emotion:
    image: disterbia94/tips-emotion-service:latest
    environment:
      - TZ=Asia/Seoul

  exercise:
    image: disterbia94/tips-exercise-service:latest
    environment:
      - TZ=Asia/Seoul

  video:
    image: disterbia94/tips-video-service:latest
    environment:
      - TZ=Asia/Seoul
  admin:
    image: disterbia94/tips-admin-service:latest
    environment:
      - TZ=Asia/Seoul
  check:
    image: disterbia94/tips-check-service:latest
    environment:
      - TZ=Asia/Seoul
  landing:
    image: disterbia94/landing-service:latest
    environment:
      - TZ=Asia/Seoul

networks:
  default:
    name: tips-network