version: '3.8'
services:
  gateway:
    image: disterbia94/tips-gateway:latest
    environment:
      - TZ=Asia/Seoul
    ports:
      - "40000:40000"
    depends_on:
      - inquire
      - email
      - user
  inquire:
    image: disterbia94/tips-inquire-service:latest
    environment:
      - TZ=Asia/Seoul
  email:
    image: disterbia94/tips-email-service:latest
    environment:
      - TZ=Asia/Seoul
  user:
    image: disterbia94/tips-user-service:latest
    environment:
      - TZ=Asia/Seoul

networks:
  default:
    name: tips-network