definitions:
  core.BasicResponse:
    properties:
      code:
        type: string
    type: object
  core.ErrorResponse:
    properties:
      err:
        type: string
    type: object
  core.ExerciseRequest:
    properties:
      end_at:
        example: YYYY-MM:dd
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      name:
        type: string
      start_at:
        example: YYYY-MM-dd
        type: string
      times:
        example:
        - HH:mm
        - HH:mm
        items:
          type: string
        type: array
      weekdays:
        items:
          type: integer
        type: array
    type: object
  core.ExerciseResponse:
    properties:
      end_at:
        example: YYYY-MM:dd
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      name:
        type: string
      start_at:
        example: YYYY-MM-dd
        type: string
      times:
        items:
          type: string
        type: array
      weekdays:
        items:
          type: integer
        type: array
    type: object
  core.ExerciseTakeResponse:
    properties:
      Exercise_taken:
        items:
          $ref: '#/definitions/core.ExpectExerciseResponse'
        type: array
      date_taken:
        example: YYYY-MM-dd
        type: string
    type: object
  core.ExpectExerciseResponse:
    properties:
      id:
        type: integer
      name:
        type: string
      time_taken:
        additionalProperties:
          type: integer
        type: object
    type: object
  core.ProjectResponse:
    properties:
      count:
        type: integer
      name:
        type: string
      project_id:
        type: string
    type: object
  core.TakeExercise:
    properties:
      date_taken:
        example: YYYY-MM-DD
        type: string
      exercise_id:
        type: integer
      time_taken:
        example: HH:mm
        type: string
    type: object
  core.VideoResponse:
    properties:
      duration:
        type: integer
      name:
        type: string
      thumbnail_url:
        type: string
      video_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /do-exercises:
    post:
      consumes:
      - application/json
      description: 운동 완료 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 운동 완료 데이터
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/core.TakeExercise'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/core.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
      summary: 운동 기록
      tags:
      - 운동 /exercise
  /get-exercises:
    get:
      description: 등록 운동 조회시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 등록 운동 정보
          schema:
            items:
              $ref: '#/definitions/core.ExerciseResponse'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
      summary: 등록 운동 조회
      tags:
      - 운동 /exercise
  /get-projects:
    get:
      description: 운동 동영상 카테고리 조회시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 카테고리 정보
          schema:
            items:
              $ref: '#/definitions/core.ProjectResponse'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
      summary: 운동 동영상 카테고리 조회
      tags:
      - 운동 /exercise
  /get-takens:
    get:
      description: 운동 내역 조회시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 운동 내역정보
          schema:
            items:
              $ref: '#/definitions/core.ExerciseTakeResponse'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
      summary: 운동 내역 조회
      tags:
      - 운동 /exercise
  /get-videos:
    get:
      description: 카테고리별 운동 동영상 조회시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: project_id
        in: query
        name: project_id
        required: true
        type: string
      - description: 페이지 default 0
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 동영상 정보
          schema:
            items:
              $ref: '#/definitions/core.VideoResponse'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
      summary: 카테고리별 운동 동영상 조회 (20개씩)
      tags:
      - 운동 /exercise
  /remove-exercise/{id}:
    post:
      consumes:
      - application/json
      description: 운동 삭제시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 삭제할 id 배열
        in: body
        name: request
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/core.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
      summary: 운동 삭제
      tags:
      - 운동 /exercise
  /save-exercise:
    post:
      description: 운동 등록 및 수정시 호출 - 생성시 id생략
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 요청 DTO - 운동 데이터
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/core.ExerciseRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/core.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
      summary: 운동 저장
      tags:
      - 운동 /exercise
  /undo-exercise/{id}:
    post:
      consumes:
      - application/json
      description: 운동 취소시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 취소 ID
        in: path
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/core.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
      summary: 운동 기록
      tags:
      - 운동 /exercise
swagger: "2.0"
