definitions:
  core.BasicResponse:
    properties:
      code:
        type: string
    type: object
  core.ErrorResponse:
    properties:
      err:
        type: string
    type: object
  core.MessageResponse:
    properties:
      body:
        example: 알람내용
        type: string
      created_at:
        example: 'YYYY-mm-dd HH:mm:ss '
        type: string
      id:
        type: integer
      is_read:
        type: boolean
      parent_id:
        type: integer
      type:
        type: integer
    type: object
info:
  contact: {}
paths:
  /get-messages:
    get:
      description: 수신 알림 조회시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 알람정보 - type 1:수면 2:운동
          schema:
            items:
              $ref: '#/definitions/core.MessageResponse'
            type: array
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
      summary: 수신 알림 조회
      tags:
      - 알람 /alarm
  /read-messages:
    post:
      consumes:
      - application/json
      description: 수신 알림 조회시 자동 읽음 처리라면 수신 알림 조회완료 후 함께 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/core.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
      summary: 알림 모두 읽기
      tags:
      - 알람 /alarm
  /remove-messages:
    post:
      consumes:
      - application/json
      description: 수신된 알림 삭제시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 삭제할 id 배열
        in: body
        name: request
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/core.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
      summary: 수신된 알림 삭제
      tags:
      - 알람 /alarm
swagger: "2.0"
