// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/get-face-scores": {
            "get": {
                "description": "표정검사 점수 조회시 호출",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "검사 /check"
                ],
                "summary": "표정검사 점수 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {jwt_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "시작날짜 yyyy-mm-dd",
                        "name": "start_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "종료날짜 yyyy-mm-dd",
                        "name": "end_date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "점수정보 - face_type: 1-기쁨 2-슬픔 3-놀람 4-분노",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/core.FaceScoreResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/get-scores": {
            "get": {
                "description": "손가락태핑/눈깜빡임 점수 조회시 호출",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "검사 /check"
                ],
                "summary": "손가락태핑/눈깜빡임 점수 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {jwt_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "1-손가락태핑 2-눈깜빡임",
                        "name": "score_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "시작날짜 yyyy-mm-dd",
                        "name": "start_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "종료날짜 yyyy-mm-dd",
                        "name": "end_date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "점수정보",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/core.TapBlinkResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/get-videos": {
            "get": {
                "description": "샘플동영상 조회시 호출",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "검사 /check"
                ],
                "summary": "샘플동영상 전체 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {jwt_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "동영상 정보 - category: 1-표정 2-손가락태핑 3-눈깜빡임 / video_type: 1-태핑,눈깜빡임,기쁨 2-슬픔 3-놀람 4-분노",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/core.SampleVideoResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/save-face-score": {
            "post": {
                "description": "표정검사 완료 후 호출",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "검사 /check"
                ],
                "summary": "표정검사 점수 저장",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {jwt_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "요청 DTO - face_type: 1-기쁨 2-슬픔 3-놀람 4-분노",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core.FaceScoreRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공시 200 반환",
                        "schema": {
                            "$ref": "#/definitions/core.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/save-score": {
            "post": {
                "description": "손가락태핑/눈깜빡임 검사 완료 후 호출",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "검사 /check"
                ],
                "summary": "손가락태핑/눈깜빡임 검사 점수 저장",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {jwt_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "요청 DTO - score_type: 1-손가락태핑 2-눈깜빡임",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core.TapBlinkRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공시 200 반환",
                        "schema": {
                            "$ref": "#/definitions/core.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "core.BasicResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "core.ErrorResponse": {
            "type": "object",
            "properties": {
                "err": {
                    "type": "string"
                }
            }
        },
        "core.FaceScoreRequest": {
            "type": "object",
            "required": [
                "face_line",
                "face_type",
                "sd"
            ],
            "properties": {
                "face_line": {
                    "type": "integer",
                    "maximum": 8,
                    "minimum": 5
                },
                "face_type": {
                    "type": "integer",
                    "maximum": 8,
                    "minimum": 5
                },
                "sd": {
                    "type": "number",
                    "maximum": 100,
                    "minimum": 1
                }
            }
        },
        "core.FaceScoreResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string",
                    "example": "YYYY-mm-dd"
                },
                "face_line": {
                    "type": "integer"
                },
                "face_type": {
                    "type": "integer"
                },
                "sd": {
                    "type": "number"
                }
            }
        },
        "core.SampleVideoResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "video_id": {
                    "type": "string"
                },
                "video_type": {
                    "type": "integer"
                }
            }
        },
        "core.TapBlinkRequest": {
            "type": "object",
            "required": [
                "error_count",
                "reaction_speed",
                "score_type",
                "success_count"
            ],
            "properties": {
                "error_count": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 1
                },
                "reaction_speed": {
                    "type": "number",
                    "maximum": 100,
                    "minimum": 1
                },
                "score_type": {
                    "type": "integer",
                    "maximum": 2,
                    "minimum": 1
                },
                "success_count": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 1
                }
            }
        },
        "core.TapBlinkResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string",
                    "example": "YYYY-mm-dd"
                },
                "error_count": {
                    "type": "integer"
                },
                "reaction_speed": {
                    "type": "number"
                },
                "score_type": {
                    "type": "integer"
                },
                "success_count": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
